/*
 * generated by Xtext
 */
package org.eclipse.incquery.patternlanguage.mondix;

import org.eclipse.xtext.xbase.typesystem.legacy.XbaseBatchTypeProvider;
import org.eclipse.xtext.xbase.typing.ITypeProvider;

import com.google.inject.Binder;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MondixPatternLanguageRuntimeModule extends org.eclipse.incquery.patternlanguage.mondix.AbstractMondixPatternLanguageRuntimeModule {

	@Override
	public void configure(Binder binder) {
		super.configure(binder);
		binder.bind(ITypeProvider.class).to(XbaseBatchTypeProvider.class); // XXX IncQuery workaround to avoid "No implementation for org.eclipse.xtext.xbase.typing.ITypeProvider was bound"
	}

}
