/*
 * generated by Xtext
 */
package org.eclipse.incquery.patternlanguage.mondix;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MondixPatternLanguageRuntimeModule extends org.eclipse.incquery.patternlanguage.mondix.AbstractMondixPatternLanguageRuntimeModule {

}
