/**
 * generated by Xtext 2.9.0.rc2
 */
package org.eclipse.incquery.patternlanguage.rdf.scoping;

import org.eclipse.incquery.patternlanguage.rdf.scoping.AbstractRdfPatternLanguageScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class RdfPatternLanguageScopeProvider extends AbstractRdfPatternLanguageScopeProvider {
}
