/*
 * generated by Xtext
 */
package hu.bme.mit.incqueryd.arch.language.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ArchLanguageUiModule extends hu.bme.mit.incqueryd.arch.language.ui.AbstractArchLanguageUiModule {
	public ArchLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
