/*
 * generated by Xtext
 */
package hu.bme.mit.incqueryd.arch.language.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.LanguageSpecific;
import org.eclipse.xtext.ui.editor.IURIEditorOpener;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ArchLanguageUiModule extends AbstractArchLanguageUiModule {

	public ArchLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	@Override
    public void configureLanguageSpecificURIEditorOpener(com.google.inject.Binder binder) {
        binder.bind(IURIEditorOpener.class).annotatedWith(LanguageSpecific.class).to(RecipeEditorOpener.class);
    }

}
