/*
 * generated by Xtext 2.9.0.beta5
 */
package org.eclipse.incquery.patternlanguage.rdf


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RdfPatternLanguageStandaloneSetup extends RdfPatternLanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new RdfPatternLanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}

}
