/**
 * generated by Xtext 2.9.0.beta5
 */
package org.eclipse.incquery.patternlanguage.rdf.ui;

import org.eclipse.incquery.patternlanguage.rdf.ui.AbstractRdfPatternLanguageUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class RdfPatternLanguageUiModule extends AbstractRdfPatternLanguageUiModule {
  public RdfPatternLanguageUiModule(final AbstractUIPlugin arg0) {
    super(arg0);
  }
}
