/*
 * generated by Xtext 2.9.0.rc2
 */
package org.eclipse.incquery.patternlanguage.rdf.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractRdfPatternLanguageScopeProvider extends XbaseBatchScopeProvider {
}
