/*
 * generated by Xtext
 */
package org.eclipse.incquery.patternlanguage.mondix.ui.contentassist

import org.eclipse.incquery.patternlanguage.mondix.ui.contentassist.AbstractMondixPatternLanguageProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class MondixPatternLanguageProposalProvider extends AbstractMondixPatternLanguageProposalProvider {
}
