/*
 * generated by Xtext
 */
package hu.bme.mit.incqueryd.mondixschema.language.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MondixSchemaUiModule extends hu.bme.mit.incqueryd.mondixschema.language.ui.AbstractMondixSchemaUiModule {
	public MondixSchemaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
