/*
 * generated by Xtext
 */
package hu.bme.mit.incqueryd.arch.language.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import hu.bme.mit.incqueryd.arch.language.ui.internal.ArchLanguageActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ArchLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ArchLanguageActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ArchLanguageActivator.getInstance().getInjector(ArchLanguageActivator.HU_BME_MIT_INCQUERYD_ARCH_LANGUAGE_ARCHLANGUAGE);
	}
	
}
