/*
 * generated by Xtext 2.9.0.beta5
 */
package org.eclipse.incquery.patternlanguage.rdf.ui.tests;

import com.google.inject.Injector;
import org.eclipse.incquery.patternlanguage.rdf.ui.internal.RdfPatternLanguageActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class RdfPatternLanguageUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RdfPatternLanguageActivator.getInstance().getInjector("org.eclipse.incquery.patternlanguage.rdf.RdfPatternLanguage");
	}

}
