/*
* generated by Xtext
*/
package hu.bme.mit.incqueryd.arch.language.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ArchLanguageAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("hu/bme/mit/incqueryd/arch/language/parser/antlr/internal/InternalArchLanguage.tokens");
	}
}
