<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="arch" nsURI="http://incquery.net/arch" nsPrefix="arch">
  <eClassifiers xsi:type="ecore:EClass" name="Configuration" eSuperTypes="#//ElementWithTraceInfo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="clusters" upperBound="-1"
        eType="ecore:EClass infrastructure.ecore#//Cluster" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reteRecipes" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.incquery.runtime.rete.recipes/model/rete-recipes.xcore#/EPackage/ReteRecipe"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" upperBound="-1"
        eType="#//InfrastructureMapping" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InfrastructureMapping" eSuperTypes="#//ElementWithTraceInfo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappedElements" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.incquery.runtime.rete.recipes/model/rete-recipes.xcore#/EPackage/ReteNodeRecipe"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetElement" eType="ecore:EClass infrastructure.ecore#//InfrastructureNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementWithTraceInfo" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="traceInfo" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
