/**
 * generated by Xtext 2.9.0.beta5
 */
package org.eclipse.incquery.patternlanguage.rdf.web;

import com.google.inject.Provider;
import java.util.concurrent.ExecutorService;
import org.eclipse.incquery.patternlanguage.rdf.web.AbstractRdfPatternLanguageWebModule;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register additional components to be used within the web application.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class RdfPatternLanguageWebModule extends AbstractRdfPatternLanguageWebModule {
  public RdfPatternLanguageWebModule(final Provider<ExecutorService> executorServiceProvider) {
    super(executorServiceProvider);
  }
}
