/**
 * generated by Xtext 2.9.0.beta5
 */
package org.eclipse.incquery.patternlanguage.rdf.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.google.inject.Module;
import com.google.inject.Provider;
import com.google.inject.util.Modules;
import java.util.concurrent.ExecutorService;
import org.eclipse.incquery.patternlanguage.rdf.RdfPatternLanguageRuntimeModule;
import org.eclipse.incquery.patternlanguage.rdf.RdfPatternLanguageStandaloneSetup;
import org.eclipse.incquery.patternlanguage.rdf.web.RdfPatternLanguageWebModule;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class RdfPatternLanguageWebSetup extends RdfPatternLanguageStandaloneSetup {
  private final Provider<ExecutorService> executorServiceProvider;
  
  @Override
  public Injector createInjector() {
    final RdfPatternLanguageRuntimeModule runtimeModule = new RdfPatternLanguageRuntimeModule();
    final RdfPatternLanguageWebModule webModule = new RdfPatternLanguageWebModule(this.executorServiceProvider);
    Modules.OverriddenModuleBuilder _override = Modules.override(runtimeModule);
    Module _with = _override.with(webModule);
    return Guice.createInjector(_with);
  }
  
  public RdfPatternLanguageWebSetup(final Provider<ExecutorService> executorServiceProvider) {
    super();
    this.executorServiceProvider = executorServiceProvider;
  }
}
