/*
 * generated by Xtext
 */
package hu.bme.mit.incqueryd.mondixschema.language.ui.contentassist

import hu.bme.mit.incqueryd.mondixschema.language.ui.contentassist.AbstractMondixSchemaProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class MondixSchemaProposalProvider extends AbstractMondixSchemaProposalProvider {
}
