/*
 * generated by Xtext 2.9.0.beta5
 */
package org.eclipse.incquery.patternlanguage.rdf.web;

import com.google.inject.Binder;
import com.google.inject.Provider;
import com.google.inject.name.Names;
import java.util.concurrent.ExecutorService;
import org.eclipse.incquery.patternlanguage.rdf.ide.contentassist.antlr.RdfPatternLanguageParser;
import org.eclipse.incquery.patternlanguage.rdf.ide.contentassist.antlr.internal.InternalRdfPatternLanguageLexer;
import org.eclipse.xtext.ide.LexerIdeBindings;
import org.eclipse.xtext.ide.editor.contentassist.antlr.IContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.Lexer;
import org.eclipse.xtext.xbase.web.DefaultXbaseWebModule;

/**
 * Manual modifications go to {@link RdfPatternLanguageWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractRdfPatternLanguageWebModule extends DefaultXbaseWebModule {

	public AbstractRdfPatternLanguageWebModule(Provider<ExecutorService> executorServiceProvider) {
		super(executorServiceProvider);
	}
	
	// contributed by org.eclipse.xtext.xtext.generator.web.WebIntegrationFragment
	public void configureContentAssistLexer(Binder binder) {
		binder.bind(Lexer.class).annotatedWith(Names.named(LexerIdeBindings.CONTENT_ASSIST)).to(InternalRdfPatternLanguageLexer.class);
	}
	
	// contributed by org.eclipse.xtext.xtext.generator.web.WebIntegrationFragment
	public Class<? extends IContentAssistParser> bindIContentAssistParser() {
		return RdfPatternLanguageParser.class;
	}
	
}
