/*
 * generated by Xtext
 */
package org.eclipse.incquery.patternlanguage.rdf;

import org.eclipse.incquery.patternlanguage.rdf.conversion.RdfPatternLanguageValueConverterService;
import org.eclipse.incquery.patternlanguage.typing.ITypeInferrer;
import org.eclipse.incquery.patternlanguage.typing.ITypeInferrer.NullTypeInferrer;
import org.eclipse.incquery.patternlanguage.typing.ITypeSystem;
import org.eclipse.incquery.patternlanguage.typing.ITypeSystem.NullTypeSystem;
import org.eclipse.xtext.conversion.IValueConverterService;

import com.google.inject.Binder;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class RdfPatternLanguageRuntimeModule extends org.eclipse.incquery.patternlanguage.rdf.AbstractRdfPatternLanguageRuntimeModule {

	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService() {
		return RdfPatternLanguageValueConverterService.class;
	}

	@Override
	public void configure(Binder binder) {
		super.configure(binder);
		// XXX IncQuery workarounds
		binder.bind(ITypeInferrer.class).to(NullTypeInferrer.class);
		binder.bind(ITypeSystem.class).to(NullTypeSystem.class);
	}

}
