/*
 * generated by Xtext
 */
package org.eclipse.incquery.patternlanguage.rdf.ui.contentassist

import org.eclipse.incquery.patternlanguage.rdf.ui.contentassist.AbstractRdfPatternLanguageProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class RdfPatternLanguageProposalProvider extends AbstractRdfPatternLanguageProposalProvider {
}
