/*
* generated by Xtext
*/
package hu.bme.mit.incqueryd.mondixschema.language;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MondixSchemaUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return hu.bme.mit.incqueryd.mondixschema.language.ui.internal.MondixSchemaActivator.getInstance().getInjector("hu.bme.mit.incqueryd.mondixschema.language.MondixSchema");
	}
	
}
