/**
 * generated by Xtext 2.9.0.beta5
 */
package org.eclipse.incquery.patternlanguage.rdf.formatting2;

import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;

@SuppressWarnings("all")
public class RdfPatternLanguageFormatter extends AbstractFormatter2 {
  @Override
  public void format(final Object obj, final IFormattableDocument document) {
  }
}
