/*
* generated by Xtext
*/
package org.eclipse.incquery.patternlanguage.rdf.validation;

import org.eclipse.incquery.patternlanguage.patternLanguage.PatternModel;

/**
 * Custom validation rules.
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
public class RdfPatternLanguageJavaValidator extends org.eclipse.incquery.patternlanguage.rdf.validation.AbstractRdfPatternLanguageJavaValidator {

//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital", MyDslPackage.Literals.GREETING__NAME);
//		}
//	}

	@Override
	public void checkPackageDeclaration(PatternModel model) {
		// Do not check
	}

}
