/*
* generated by Xtext
*/
package hu.bme.mit.incqueryd.mondixschema.language.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MondixSchemaAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("hu/bme/mit/incqueryd/mondixschema/language/parser/antlr/internal/InternalMondixSchema.tokens");
	}
}
