/*
* generated by Xtext
*/
package hu.bme.mit.incqueryd.mondixschema.language.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import hu.bme.mit.incqueryd.mondixschema.language.services.MondixSchemaGrammarAccess;

public class MondixSchemaParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private MondixSchemaGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected hu.bme.mit.incqueryd.mondixschema.language.parser.antlr.internal.InternalMondixSchemaParser createParser(XtextTokenStream stream) {
		return new hu.bme.mit.incqueryd.mondixschema.language.parser.antlr.internal.InternalMondixSchemaParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Schema";
	}
	
	public MondixSchemaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MondixSchemaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
