/**
 * generated by Xtext
 */
package org.eclipse.incquery.patternlanguage.rdf.ui.quickfix;

import org.eclipse.incquery.patternlanguage.ui.quickfix.PatternLanguageQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class RdfPatternLanguageQuickfixProvider extends PatternLanguageQuickfixProvider {
}
