/*
* generated by Xtext
*/
package org.eclipse.incquery.patternlanguage.mondix;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MondixPatternLanguageUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.eclipse.incquery.patternlanguage.mondix.ui.internal.MondixPatternLanguageActivator.getInstance().getInjector("org.eclipse.incquery.patternlanguage.mondix.MondixPatternLanguage");
	}
	
}
