/*
 * generated by Xtext
 */
package hu.bme.mit.incqueryd.arch.language.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.ComposedChecks;

@ComposedChecks(validators= {org.eclipse.xtext.validation.ImportUriValidator.class})
public class AbstractArchLanguageValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://incquery.net/arch"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://incquery.net/d/infrastructure"));
		return result;
	}
}
