/*
* generated by Xtext
*/
package org.eclipse.incquery.patternlanguage.rdf.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.incquery.patternlanguage.services.PatternLanguageGrammarAccess;
import org.eclipse.xtext.xbase.services.XbaseGrammarAccess;
import org.eclipse.xtext.xbase.services.XtypeGrammarAccess;

@Singleton
public class RdfPatternLanguageGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class RdfPatternModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "RdfPatternModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPatternModelAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cBaseAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cBaseBaseParserRuleCall_1_0 = (RuleCall)cBaseAssignment_1.eContents().get(0);
		private final Assignment cPrefixesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cPrefixesPrefixParserRuleCall_2_0 = (RuleCall)cPrefixesAssignment_2.eContents().get(0);
		private final Assignment cPatternsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPatternsPatternParserRuleCall_3_0 = (RuleCall)cPatternsAssignment_3.eContents().get(0);
		
		//RdfPatternModel returns core::PatternModel:
		//	{PatternModel} base=Base? prefixes+=Prefix* patterns+=Pattern*;
		public ParserRule getRule() { return rule; }

		//{PatternModel} base=Base? prefixes+=Prefix* patterns+=Pattern*
		public Group getGroup() { return cGroup; }

		//{PatternModel}
		public Action getPatternModelAction_0() { return cPatternModelAction_0; }

		//base=Base?
		public Assignment getBaseAssignment_1() { return cBaseAssignment_1; }

		//Base
		public RuleCall getBaseBaseParserRuleCall_1_0() { return cBaseBaseParserRuleCall_1_0; }

		//prefixes+=Prefix*
		public Assignment getPrefixesAssignment_2() { return cPrefixesAssignment_2; }

		//Prefix
		public RuleCall getPrefixesPrefixParserRuleCall_2_0() { return cPrefixesPrefixParserRuleCall_2_0; }

		//patterns+=Pattern*
		public Assignment getPatternsAssignment_3() { return cPatternsAssignment_3; }

		//Pattern
		public RuleCall getPatternsPatternParserRuleCall_3_0() { return cPatternsPatternParserRuleCall_3_0; }
	}

	public class BaseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Base");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBaseKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cIriAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIriRawIriParserRuleCall_1_0 = (RuleCall)cIriAssignment_1.eContents().get(0);
		
		//Base:
		//	"base" iri=RawIri;
		public ParserRule getRule() { return rule; }

		//"base" iri=RawIri
		public Group getGroup() { return cGroup; }

		//"base"
		public Keyword getBaseKeyword_0() { return cBaseKeyword_0; }

		//iri=RawIri
		public Assignment getIriAssignment_1() { return cIriAssignment_1; }

		//RawIri
		public RuleCall getIriRawIriParserRuleCall_1_0() { return cIriRawIriParserRuleCall_1_0; }
	}

	public class PrefixElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Prefix");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPrefixKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cIriAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cIriRawIriParserRuleCall_3_0 = (RuleCall)cIriAssignment_3.eContents().get(0);
		
		//Prefix:
		//	"prefix" name=ID ":" iri=RawIri;
		public ParserRule getRule() { return rule; }

		//"prefix" name=ID ":" iri=RawIri
		public Group getGroup() { return cGroup; }

		//"prefix"
		public Keyword getPrefixKeyword_0() { return cPrefixKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//":"
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }

		//iri=RawIri
		public Assignment getIriAssignment_3() { return cIriAssignment_3; }

		//RawIri
		public RuleCall getIriRawIriParserRuleCall_3_0() { return cIriRawIriParserRuleCall_3_0; }
	}

	public class IriElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Iri");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Assignment cPrefixAssignment_0_0 = (Assignment)cGroup_0.eContents().get(0);
		private final CrossReference cPrefixPrefixCrossReference_0_0_0 = (CrossReference)cPrefixAssignment_0_0.eContents().get(0);
		private final RuleCall cPrefixPrefixIDTerminalRuleCall_0_0_0_1 = (RuleCall)cPrefixPrefixCrossReference_0_0_0.eContents().get(1);
		private final Keyword cColonKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Assignment cIriAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIriRawIriParserRuleCall_1_0 = (RuleCall)cIriAssignment_1.eContents().get(0);
		
		//Iri:
		//	(prefix=[Prefix] ":")? iri=RawIri;
		public ParserRule getRule() { return rule; }

		//(prefix=[Prefix] ":")? iri=RawIri
		public Group getGroup() { return cGroup; }

		//(prefix=[Prefix] ":")?
		public Group getGroup_0() { return cGroup_0; }

		//prefix=[Prefix]
		public Assignment getPrefixAssignment_0_0() { return cPrefixAssignment_0_0; }

		//[Prefix]
		public CrossReference getPrefixPrefixCrossReference_0_0_0() { return cPrefixPrefixCrossReference_0_0_0; }

		//ID
		public RuleCall getPrefixPrefixIDTerminalRuleCall_0_0_0_1() { return cPrefixPrefixIDTerminalRuleCall_0_0_0_1; }

		//":"
		public Keyword getColonKeyword_0_1() { return cColonKeyword_0_1; }

		//iri=RawIri
		public Assignment getIriAssignment_1() { return cIriAssignment_1; }

		//RawIri
		public RuleCall getIriRawIriParserRuleCall_1_0() { return cIriRawIriParserRuleCall_1_0; }
	}

	public class ConstraintElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Constraint");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cCompareConstraintParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cPatternCompositionConstraintParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cTypeConstraintParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cRdfPathExpressionConstraintParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cRdfCheckConstraintParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//Constraint returns core::Constraint:
		//	CompareConstraint | PatternCompositionConstraint | TypeConstraint | RdfPathExpressionConstraint | RdfCheckConstraint;
		public ParserRule getRule() { return rule; }

		//CompareConstraint | PatternCompositionConstraint | TypeConstraint | RdfPathExpressionConstraint | RdfCheckConstraint
		public Alternatives getAlternatives() { return cAlternatives; }

		//CompareConstraint
		public RuleCall getCompareConstraintParserRuleCall_0() { return cCompareConstraintParserRuleCall_0; }

		//PatternCompositionConstraint
		public RuleCall getPatternCompositionConstraintParserRuleCall_1() { return cPatternCompositionConstraintParserRuleCall_1; }

		//TypeConstraint
		public RuleCall getTypeConstraintParserRuleCall_2() { return cTypeConstraintParserRuleCall_2; }

		//RdfPathExpressionConstraint
		public RuleCall getRdfPathExpressionConstraintParserRuleCall_3() { return cRdfPathExpressionConstraintParserRuleCall_3; }

		//RdfCheckConstraint
		public RuleCall getRdfCheckConstraintParserRuleCall_4() { return cRdfCheckConstraintParserRuleCall_4; }
	}

	public class RdfCheckConstraintElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "RdfCheckConstraint");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRdfCheckConstraintAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cCheckKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cExpressionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cExpressionSTRINGTerminalRuleCall_3_0 = (RuleCall)cExpressionAssignment_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//RdfCheckConstraint returns Constraint:
		//	{RdfCheckConstraint} "check" "(" expression=STRING ")";
		public ParserRule getRule() { return rule; }

		//{RdfCheckConstraint} "check" "(" expression=STRING ")"
		public Group getGroup() { return cGroup; }

		//{RdfCheckConstraint}
		public Action getRdfCheckConstraintAction_0() { return cRdfCheckConstraintAction_0; }

		//"check"
		public Keyword getCheckKeyword_1() { return cCheckKeyword_1; }

		//"("
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }

		//expression=STRING
		public Assignment getExpressionAssignment_3() { return cExpressionAssignment_3; }

		//STRING
		public RuleCall getExpressionSTRINGTerminalRuleCall_3_0() { return cExpressionSTRINGTerminalRuleCall_3_0; }

		//")"
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}

	public class RdfPathExpressionConstraintElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "RdfPathExpressionConstraint");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cPathExpressionAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cPathExpressionPathExpressionTailParserRuleCall_0_0 = (RuleCall)cPathExpressionAssignment_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cSrcAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cSrcVariableReferenceParserRuleCall_2_0 = (RuleCall)cSrcAssignment_2.eContents().get(0);
		private final Keyword cCommaKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cDstAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDstValueReferenceParserRuleCall_4_0 = (RuleCall)cDstAssignment_4.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//RdfPathExpressionConstraint:
		//	pathExpression=PathExpressionTail "(" src=VariableReference "," dst=ValueReference ")";
		public ParserRule getRule() { return rule; }

		//pathExpression=PathExpressionTail "(" src=VariableReference "," dst=ValueReference ")"
		public Group getGroup() { return cGroup; }

		//pathExpression=PathExpressionTail
		public Assignment getPathExpressionAssignment_0() { return cPathExpressionAssignment_0; }

		//PathExpressionTail
		public RuleCall getPathExpressionPathExpressionTailParserRuleCall_0_0() { return cPathExpressionPathExpressionTailParserRuleCall_0_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }

		//src=VariableReference
		public Assignment getSrcAssignment_2() { return cSrcAssignment_2; }

		//VariableReference
		public RuleCall getSrcVariableReferenceParserRuleCall_2_0() { return cSrcVariableReferenceParserRuleCall_2_0; }

		//","
		public Keyword getCommaKeyword_3() { return cCommaKeyword_3; }

		//dst=ValueReference
		public Assignment getDstAssignment_4() { return cDstAssignment_4; }

		//ValueReference
		public RuleCall getDstValueReferenceParserRuleCall_4_0() { return cDstValueReferenceParserRuleCall_4_0; }

		//")"
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
	}

	public class TypeConstraintElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TypeConstraint");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTypeTypeParserRuleCall_0_0 = (RuleCall)cTypeAssignment_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cVarAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cVarVariableReferenceParserRuleCall_2_0 = (RuleCall)cVarAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//TypeConstraint:
		//	type=Type "(" var=VariableReference ")";
		public ParserRule getRule() { return rule; }

		//type=Type "(" var=VariableReference ")"
		public Group getGroup() { return cGroup; }

		//type=Type
		public Assignment getTypeAssignment_0() { return cTypeAssignment_0; }

		//Type
		public RuleCall getTypeTypeParserRuleCall_0_0() { return cTypeTypeParserRuleCall_0_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }

		//var=VariableReference
		public Assignment getVarAssignment_2() { return cVarAssignment_2; }

		//VariableReference
		public RuleCall getVarVariableReferenceParserRuleCall_2_0() { return cVarVariableReferenceParserRuleCall_2_0; }

		//")"
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
	}

	public class TypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Type");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cClassAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cClassAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cClassIriParserRuleCall_1_0 = (RuleCall)cClassAssignment_1.eContents().get(0);
		
		//Type returns core::EntityType:
		//	{Class} class=Iri;
		public ParserRule getRule() { return rule; }

		//{Class} class=Iri
		public Group getGroup() { return cGroup; }

		//{Class}
		public Action getClassAction_0() { return cClassAction_0; }

		//class=Iri
		public Assignment getClassAssignment_1() { return cClassAssignment_1; }

		//Iri
		public RuleCall getClassIriParserRuleCall_1_0() { return cClassIriParserRuleCall_1_0; }
	}

	public class RefTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "RefType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPropertyAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cPropertyAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cPropertyIriParserRuleCall_1_0 = (RuleCall)cPropertyAssignment_1.eContents().get(0);
		
		//RefType returns core::RelationType:
		//	{Property} property=Iri;
		public ParserRule getRule() { return rule; }

		//{Property} property=Iri
		public Group getGroup() { return cGroup; }

		//{Property}
		public Action getPropertyAction_0() { return cPropertyAction_0; }

		//property=Iri
		public Assignment getPropertyAssignment_1() { return cPropertyAssignment_1; }

		//Iri
		public RuleCall getPropertyIriParserRuleCall_1_0() { return cPropertyIriParserRuleCall_1_0; }
	}

	public class LiteralValueReferenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "LiteralValueReference");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cIntValueParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cStringValueParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cDoubleValueParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cBoolValueParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cRdfLiteralParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//LiteralValueReference returns core::ValueReference:
		//	IntValue | StringValue | DoubleValue | // Copied from PatternLanguage
		//	BoolValue | // Additions
		//	RdfLiteral;
		public ParserRule getRule() { return rule; }

		//IntValue | StringValue | DoubleValue | // Copied from PatternLanguage
		//BoolValue | // Additions
		//RdfLiteral
		public Alternatives getAlternatives() { return cAlternatives; }

		//IntValue
		public RuleCall getIntValueParserRuleCall_0() { return cIntValueParserRuleCall_0; }

		//StringValue
		public RuleCall getStringValueParserRuleCall_1() { return cStringValueParserRuleCall_1; }

		//DoubleValue
		public RuleCall getDoubleValueParserRuleCall_2() { return cDoubleValueParserRuleCall_2; }

		//// Copied from PatternLanguage
		//BoolValue
		public RuleCall getBoolValueParserRuleCall_3() { return cBoolValueParserRuleCall_3; }

		//// Additions
		//RdfLiteral
		public RuleCall getRdfLiteralParserRuleCall_4() { return cRdfLiteralParserRuleCall_4; }
	}

	public class RdfLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "RdfLiteral");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cLexicalFormAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cLexicalFormSTRINGTerminalRuleCall_0_0 = (RuleCall)cLexicalFormAssignment_0.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cAlternatives_1.eContents().get(0);
		private final Keyword cCircumflexAccentCircumflexAccentKeyword_1_0_0 = (Keyword)cGroup_1_0.eContents().get(0);
		private final Assignment cDatatypeAssignment_1_0_1 = (Assignment)cGroup_1_0.eContents().get(1);
		private final RuleCall cDatatypeIriParserRuleCall_1_0_1_0 = (RuleCall)cDatatypeAssignment_1_0_1.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cAlternatives_1.eContents().get(1);
		private final Keyword cCommercialAtKeyword_1_1_0 = (Keyword)cGroup_1_1.eContents().get(0);
		private final Assignment cLanguageAssignment_1_1_1 = (Assignment)cGroup_1_1.eContents().get(1);
		private final RuleCall cLanguageIDTerminalRuleCall_1_1_1_0 = (RuleCall)cLanguageAssignment_1_1_1.eContents().get(0);
		
		//RdfLiteral:
		//	lexicalForm=STRING ("^^" datatype=Iri | "@" language=ID);
		public ParserRule getRule() { return rule; }

		//lexicalForm=STRING ("^^" datatype=Iri | "@" language=ID)
		public Group getGroup() { return cGroup; }

		//lexicalForm=STRING
		public Assignment getLexicalFormAssignment_0() { return cLexicalFormAssignment_0; }

		//STRING
		public RuleCall getLexicalFormSTRINGTerminalRuleCall_0_0() { return cLexicalFormSTRINGTerminalRuleCall_0_0; }

		//"^^" datatype=Iri | "@" language=ID
		public Alternatives getAlternatives_1() { return cAlternatives_1; }

		//"^^" datatype=Iri
		public Group getGroup_1_0() { return cGroup_1_0; }

		//"^^"
		public Keyword getCircumflexAccentCircumflexAccentKeyword_1_0_0() { return cCircumflexAccentCircumflexAccentKeyword_1_0_0; }

		//datatype=Iri
		public Assignment getDatatypeAssignment_1_0_1() { return cDatatypeAssignment_1_0_1; }

		//Iri
		public RuleCall getDatatypeIriParserRuleCall_1_0_1_0() { return cDatatypeIriParserRuleCall_1_0_1_0; }

		//"@" language=ID
		public Group getGroup_1_1() { return cGroup_1_1; }

		//"@"
		public Keyword getCommercialAtKeyword_1_1_0() { return cCommercialAtKeyword_1_1_0; }

		//language=ID
		public Assignment getLanguageAssignment_1_1_1() { return cLanguageAssignment_1_1_1; }

		//ID
		public RuleCall getLanguageIDTerminalRuleCall_1_1_1_0() { return cLanguageIDTerminalRuleCall_1_1_1_0; }
	}

	public class RawIriElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "RawIri");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cESCAPED_IRITerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//RawIri returns ecore::EString:
		//	ID | ESCAPED_IRI;
		public ParserRule getRule() { return rule; }

		//ID | ESCAPED_IRI
		public Alternatives getAlternatives() { return cAlternatives; }

		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }

		//ESCAPED_IRI
		public RuleCall getESCAPED_IRITerminalRuleCall_1() { return cESCAPED_IRITerminalRuleCall_1; }
	}
	
	
	private RdfPatternModelElements pRdfPatternModel;
	private BaseElements pBase;
	private PrefixElements pPrefix;
	private IriElements pIri;
	private ConstraintElements pConstraint;
	private RdfCheckConstraintElements pRdfCheckConstraint;
	private RdfPathExpressionConstraintElements pRdfPathExpressionConstraint;
	private TypeConstraintElements pTypeConstraint;
	private TypeElements pType;
	private RefTypeElements pRefType;
	private LiteralValueReferenceElements pLiteralValueReference;
	private RdfLiteralElements pRdfLiteral;
	private RawIriElements pRawIri;
	private TerminalRule tESCAPED_IRI;
	
	private final Grammar grammar;

	private PatternLanguageGrammarAccess gaPatternLanguage;

	@Inject
	public RdfPatternLanguageGrammarAccess(GrammarProvider grammarProvider,
		PatternLanguageGrammarAccess gaPatternLanguage) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaPatternLanguage = gaPatternLanguage;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.eclipse.incquery.patternlanguage.rdf.RdfPatternLanguage".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public PatternLanguageGrammarAccess getPatternLanguageGrammarAccess() {
		return gaPatternLanguage;
	}

	
	//RdfPatternModel returns core::PatternModel:
	//	{PatternModel} base=Base? prefixes+=Prefix* patterns+=Pattern*;
	public RdfPatternModelElements getRdfPatternModelAccess() {
		return (pRdfPatternModel != null) ? pRdfPatternModel : (pRdfPatternModel = new RdfPatternModelElements());
	}
	
	public ParserRule getRdfPatternModelRule() {
		return getRdfPatternModelAccess().getRule();
	}

	//Base:
	//	"base" iri=RawIri;
	public BaseElements getBaseAccess() {
		return (pBase != null) ? pBase : (pBase = new BaseElements());
	}
	
	public ParserRule getBaseRule() {
		return getBaseAccess().getRule();
	}

	//Prefix:
	//	"prefix" name=ID ":" iri=RawIri;
	public PrefixElements getPrefixAccess() {
		return (pPrefix != null) ? pPrefix : (pPrefix = new PrefixElements());
	}
	
	public ParserRule getPrefixRule() {
		return getPrefixAccess().getRule();
	}

	//Iri:
	//	(prefix=[Prefix] ":")? iri=RawIri;
	public IriElements getIriAccess() {
		return (pIri != null) ? pIri : (pIri = new IriElements());
	}
	
	public ParserRule getIriRule() {
		return getIriAccess().getRule();
	}

	//Constraint returns core::Constraint:
	//	CompareConstraint | PatternCompositionConstraint | TypeConstraint | RdfPathExpressionConstraint | RdfCheckConstraint;
	public ConstraintElements getConstraintAccess() {
		return (pConstraint != null) ? pConstraint : (pConstraint = new ConstraintElements());
	}
	
	public ParserRule getConstraintRule() {
		return getConstraintAccess().getRule();
	}

	//RdfCheckConstraint returns Constraint:
	//	{RdfCheckConstraint} "check" "(" expression=STRING ")";
	public RdfCheckConstraintElements getRdfCheckConstraintAccess() {
		return (pRdfCheckConstraint != null) ? pRdfCheckConstraint : (pRdfCheckConstraint = new RdfCheckConstraintElements());
	}
	
	public ParserRule getRdfCheckConstraintRule() {
		return getRdfCheckConstraintAccess().getRule();
	}

	//RdfPathExpressionConstraint:
	//	pathExpression=PathExpressionTail "(" src=VariableReference "," dst=ValueReference ")";
	public RdfPathExpressionConstraintElements getRdfPathExpressionConstraintAccess() {
		return (pRdfPathExpressionConstraint != null) ? pRdfPathExpressionConstraint : (pRdfPathExpressionConstraint = new RdfPathExpressionConstraintElements());
	}
	
	public ParserRule getRdfPathExpressionConstraintRule() {
		return getRdfPathExpressionConstraintAccess().getRule();
	}

	//TypeConstraint:
	//	type=Type "(" var=VariableReference ")";
	public TypeConstraintElements getTypeConstraintAccess() {
		return (pTypeConstraint != null) ? pTypeConstraint : (pTypeConstraint = new TypeConstraintElements());
	}
	
	public ParserRule getTypeConstraintRule() {
		return getTypeConstraintAccess().getRule();
	}

	//Type returns core::EntityType:
	//	{Class} class=Iri;
	public TypeElements getTypeAccess() {
		return (pType != null) ? pType : (pType = new TypeElements());
	}
	
	public ParserRule getTypeRule() {
		return getTypeAccess().getRule();
	}

	//RefType returns core::RelationType:
	//	{Property} property=Iri;
	public RefTypeElements getRefTypeAccess() {
		return (pRefType != null) ? pRefType : (pRefType = new RefTypeElements());
	}
	
	public ParserRule getRefTypeRule() {
		return getRefTypeAccess().getRule();
	}

	//LiteralValueReference returns core::ValueReference:
	//	IntValue | StringValue | DoubleValue | // Copied from PatternLanguage
	//	BoolValue | // Additions
	//	RdfLiteral;
	public LiteralValueReferenceElements getLiteralValueReferenceAccess() {
		return (pLiteralValueReference != null) ? pLiteralValueReference : (pLiteralValueReference = new LiteralValueReferenceElements());
	}
	
	public ParserRule getLiteralValueReferenceRule() {
		return getLiteralValueReferenceAccess().getRule();
	}

	//RdfLiteral:
	//	lexicalForm=STRING ("^^" datatype=Iri | "@" language=ID);
	public RdfLiteralElements getRdfLiteralAccess() {
		return (pRdfLiteral != null) ? pRdfLiteral : (pRdfLiteral = new RdfLiteralElements());
	}
	
	public ParserRule getRdfLiteralRule() {
		return getRdfLiteralAccess().getRule();
	}

	//RawIri returns ecore::EString:
	//	ID | ESCAPED_IRI;
	public RawIriElements getRawIriAccess() {
		return (pRawIri != null) ? pRawIri : (pRawIri = new RawIriElements());
	}
	
	public ParserRule getRawIriRule() {
		return getRawIriAccess().getRule();
	}

	//terminal ESCAPED_IRI:
	//	"<" ("\\>" | !">")* ">";
	public TerminalRule getESCAPED_IRIRule() {
		return (tESCAPED_IRI != null) ? tESCAPED_IRI : (tESCAPED_IRI = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "ESCAPED_IRI"));
	} 

	//PatternModel:
	//	("package" packageName=QualifiedName)? patterns+=Pattern*;
	public PatternLanguageGrammarAccess.PatternModelElements getPatternModelAccess() {
		return gaPatternLanguage.getPatternModelAccess();
	}
	
	public ParserRule getPatternModelRule() {
		return getPatternModelAccess().getRule();
	}

	//Pattern:
	//	annotations+=Annotation* modifiers+=Modifiers* "pattern" name=ID "(" (parameters+=Parameter (","
	//	parameters+=Parameter)*)? ")" "="? bodies+=PatternBody ("or" bodies+=PatternBody)*;
	public PatternLanguageGrammarAccess.PatternElements getPatternAccess() {
		return gaPatternLanguage.getPatternAccess();
	}
	
	public ParserRule getPatternRule() {
		return getPatternAccess().getRule();
	}

	//Annotation:
	//	"@" name=ID ("(" parameters+=AnnotationParameter ("," parameters+=AnnotationParameter)* ")")?;
	public PatternLanguageGrammarAccess.AnnotationElements getAnnotationAccess() {
		return gaPatternLanguage.getAnnotationAccess();
	}
	
	public ParserRule getAnnotationRule() {
		return getAnnotationAccess().getRule();
	}

	//AnnotationParameter:
	//	name=ID "=" value=AnnotationValueReference;
	public PatternLanguageGrammarAccess.AnnotationParameterElements getAnnotationParameterAccess() {
		return gaPatternLanguage.getAnnotationParameterAccess();
	}
	
	public ParserRule getAnnotationParameterRule() {
		return getAnnotationParameterAccess().getRule();
	}

	//Modifiers: //injective?='injective' &
	//	private?="private";
	public PatternLanguageGrammarAccess.ModifiersElements getModifiersAccess() {
		return gaPatternLanguage.getModifiersAccess();
	}
	
	public ParserRule getModifiersRule() {
		return getModifiersAccess().getRule();
	}

	//Variable returns types::JvmIdentifiableElement:
	//	{Variable} name=ID (":" type=Type)?;
	public PatternLanguageGrammarAccess.VariableElements getVariableAccess() {
		return gaPatternLanguage.getVariableAccess();
	}
	
	public ParserRule getVariableRule() {
		return getVariableAccess().getRule();
	}

	//ParameterRef returns Variable:
	//	{ParameterRef} name=ID referredParam=[Variable] (":" type=Type)?;
	public PatternLanguageGrammarAccess.ParameterRefElements getParameterRefAccess() {
		return gaPatternLanguage.getParameterRefAccess();
	}
	
	public ParserRule getParameterRefRule() {
		return getParameterRefAccess().getRule();
	}

	//Parameter returns Variable:
	//	name=ID (":" type=Type)?;
	public PatternLanguageGrammarAccess.ParameterElements getParameterAccess() {
		return gaPatternLanguage.getParameterAccess();
	}
	
	public ParserRule getParameterRule() {
		return getParameterAccess().getRule();
	}

	//LocalVariable returns Variable:
	//	{LocalVariable} name=ID (":" type=Type)?;
	public PatternLanguageGrammarAccess.LocalVariableElements getLocalVariableAccess() {
		return gaPatternLanguage.getLocalVariableAccess();
	}
	
	public ParserRule getLocalVariableRule() {
		return getLocalVariableAccess().getRule();
	}

	//VariableReference:
	//	var=ID;
	public PatternLanguageGrammarAccess.VariableReferenceElements getVariableReferenceAccess() {
		return gaPatternLanguage.getVariableReferenceAccess();
	}
	
	public ParserRule getVariableReferenceRule() {
		return getVariableReferenceAccess().getRule();
	}

	//PatternBody:
	//	{PatternBody} name=ID? "{" (constraints+=Constraint ";")* "}";
	public PatternLanguageGrammarAccess.PatternBodyElements getPatternBodyAccess() {
		return gaPatternLanguage.getPatternBodyAccess();
	}
	
	public ParserRule getPatternBodyRule() {
		return getPatternBodyAccess().getRule();
	}

	//PatternCompositionConstraint returns Constraint:
	//	{PatternCompositionConstraint} negative?="neg"? call=PatternCall;
	public PatternLanguageGrammarAccess.PatternCompositionConstraintElements getPatternCompositionConstraintAccess() {
		return gaPatternLanguage.getPatternCompositionConstraintAccess();
	}
	
	public ParserRule getPatternCompositionConstraintRule() {
		return getPatternCompositionConstraintAccess().getRule();
	}

	////'count' 'find' patternRef=[Pattern] '(' (parameters+=ValueReference (','
	////parameters+=ValueReference)*)? ')';
	//PatternCall:
	//	"find" patternRef=[Pattern|QualifiedName] transitive?="+"? "(" (parameters+=ValueReference (","
	//	parameters+=ValueReference)*)? ")";
	public PatternLanguageGrammarAccess.PatternCallElements getPatternCallAccess() {
		return gaPatternLanguage.getPatternCallAccess();
	}
	
	public ParserRule getPatternCallRule() {
		return getPatternCallAccess().getRule();
	}

	//CompareConstraint returns Constraint:
	//	{CompareConstraint} leftOperand=ValueReference feature=CompareFeature rightOperand=ValueReference;
	public PatternLanguageGrammarAccess.CompareConstraintElements getCompareConstraintAccess() {
		return gaPatternLanguage.getCompareConstraintAccess();
	}
	
	public ParserRule getCompareConstraintRule() {
		return getCompareConstraintAccess().getRule();
	}

	//enum CompareFeature:
	//	equality="==" | inequality="!=";
	public PatternLanguageGrammarAccess.CompareFeatureElements getCompareFeatureAccess() {
		return gaPatternLanguage.getCompareFeatureAccess();
	}
	
	public EnumRule getCompareFeatureRule() {
		return getCompareFeatureAccess().getRule();
	}

	//CheckConstraint returns Constraint:
	//	{CheckConstraint} "check" "(" expression=XExpression ")";
	public PatternLanguageGrammarAccess.CheckConstraintElements getCheckConstraintAccess() {
		return gaPatternLanguage.getCheckConstraintAccess();
	}
	
	public ParserRule getCheckConstraintRule() {
		return getCheckConstraintAccess().getRule();
	}

	//PathExpressionConstraint returns Constraint:
	//	{PathExpressionConstraint} head=PathExpressionHead;
	public PatternLanguageGrammarAccess.PathExpressionConstraintElements getPathExpressionConstraintAccess() {
		return gaPatternLanguage.getPathExpressionConstraintAccess();
	}
	
	public ParserRule getPathExpressionConstraintRule() {
		return getPathExpressionConstraintAccess().getRule();
	}

	//PathExpressionHead returns PathExpressionElement:
	//	{PathExpressionHead} type=Type "." tail=PathExpressionTail "(" src=VariableReference "," dst=ValueReference ")";
	public PatternLanguageGrammarAccess.PathExpressionHeadElements getPathExpressionHeadAccess() {
		return gaPatternLanguage.getPathExpressionHeadAccess();
	}
	
	public ParserRule getPathExpressionHeadRule() {
		return getPathExpressionHeadAccess().getRule();
	}

	//PathExpressionTail returns PathExpressionElement:
	//	{PathExpressionTail} type=RefType ("[" index=INT "]")? closure?="*"? ("." tail=PathExpressionTail)?;
	public PatternLanguageGrammarAccess.PathExpressionTailElements getPathExpressionTailAccess() {
		return gaPatternLanguage.getPathExpressionTailAccess();
	}
	
	public ParserRule getPathExpressionTailRule() {
		return getPathExpressionTailAccess().getRule();
	}

	//ValueReference:
	//	LiteralValueReference | VariableValue | ComputationValue;
	public PatternLanguageGrammarAccess.ValueReferenceElements getValueReferenceAccess() {
		return gaPatternLanguage.getValueReferenceAccess();
	}
	
	public ParserRule getValueReferenceRule() {
		return getValueReferenceAccess().getRule();
	}

	//AnnotationValueReference returns ValueReference:
	//	ValueReference | ListValue;
	public PatternLanguageGrammarAccess.AnnotationValueReferenceElements getAnnotationValueReferenceAccess() {
		return gaPatternLanguage.getAnnotationValueReferenceAccess();
	}
	
	public ParserRule getAnnotationValueReferenceRule() {
		return getAnnotationValueReferenceAccess().getRule();
	}

	//IntValue returns LiteralValueReference:
	//	{IntValue} value=INTNUMBER;
	public PatternLanguageGrammarAccess.IntValueElements getIntValueAccess() {
		return gaPatternLanguage.getIntValueAccess();
	}
	
	public ParserRule getIntValueRule() {
		return getIntValueAccess().getRule();
	}

	//INTNUMBER returns ecore::EInt:
	//	"-"? INT;
	public PatternLanguageGrammarAccess.INTNUMBERElements getINTNUMBERAccess() {
		return gaPatternLanguage.getINTNUMBERAccess();
	}
	
	public ParserRule getINTNUMBERRule() {
		return getINTNUMBERAccess().getRule();
	}

	//StringValue returns LiteralValueReference:
	//	{StringValue} value=STRING;
	public PatternLanguageGrammarAccess.StringValueElements getStringValueAccess() {
		return gaPatternLanguage.getStringValueAccess();
	}
	
	public ParserRule getStringValueRule() {
		return getStringValueAccess().getRule();
	}

	//BoolValue returns LiteralValueReference:
	//	{BoolValue} value=BOOLEAN;
	public PatternLanguageGrammarAccess.BoolValueElements getBoolValueAccess() {
		return gaPatternLanguage.getBoolValueAccess();
	}
	
	public ParserRule getBoolValueRule() {
		return getBoolValueAccess().getRule();
	}

	//BOOLEAN returns ecore::EBoolean:
	//	"true" | "false" | "TRUE" | "FALSE";
	public PatternLanguageGrammarAccess.BOOLEANElements getBOOLEANAccess() {
		return gaPatternLanguage.getBOOLEANAccess();
	}
	
	public ParserRule getBOOLEANRule() {
		return getBOOLEANAccess().getRule();
	}

	//DoubleValue returns LiteralValueReference:
	//	{DoubleValue} value=DOUBLE;
	public PatternLanguageGrammarAccess.DoubleValueElements getDoubleValueAccess() {
		return gaPatternLanguage.getDoubleValueAccess();
	}
	
	public ParserRule getDoubleValueRule() {
		return getDoubleValueAccess().getRule();
	}

	//DOUBLE returns ecore::EDouble:
	//	"-"? INT "." INT;
	public PatternLanguageGrammarAccess.DOUBLEElements getDOUBLEAccess() {
		return gaPatternLanguage.getDOUBLEAccess();
	}
	
	public ParserRule getDOUBLERule() {
		return getDOUBLEAccess().getRule();
	}

	//VariableValue returns ValueReference:
	//	{VariableValue} value=VariableReference;
	public PatternLanguageGrammarAccess.VariableValueElements getVariableValueAccess() {
		return gaPatternLanguage.getVariableValueAccess();
	}
	
	public ParserRule getVariableValueRule() {
		return getVariableValueAccess().getRule();
	}

	//ListValue returns LiteralValueReference:
	//	{ListValue} "{" values+=ValueReference ("," values+=ValueReference)* "}";
	public PatternLanguageGrammarAccess.ListValueElements getListValueAccess() {
		return gaPatternLanguage.getListValueAccess();
	}
	
	public ParserRule getListValueRule() {
		return getListValueAccess().getRule();
	}

	//ComputationValue returns ValueReference:
	//	AggregatedValue | FunctionEvaluationValue;
	public PatternLanguageGrammarAccess.ComputationValueElements getComputationValueAccess() {
		return gaPatternLanguage.getComputationValueAccess();
	}
	
	public ParserRule getComputationValueRule() {
		return getComputationValueAccess().getRule();
	}

	//FunctionEvaluationValue returns ComputationValue:
	//	{FunctionEvaluationValue} "eval" "(" expression=XExpression ")";
	public PatternLanguageGrammarAccess.FunctionEvaluationValueElements getFunctionEvaluationValueAccess() {
		return gaPatternLanguage.getFunctionEvaluationValueAccess();
	}
	
	public ParserRule getFunctionEvaluationValueRule() {
		return getFunctionEvaluationValueAccess().getRule();
	}

	//AggregatedValue returns ComputationValue:
	//	{AggregatedValue} / *'aggregate'* / aggregator=AggregatorExpression call=PatternCall;
	public PatternLanguageGrammarAccess.AggregatedValueElements getAggregatedValueAccess() {
		return gaPatternLanguage.getAggregatedValueAccess();
	}
	
	public ParserRule getAggregatedValueRule() {
		return getAggregatedValueAccess().getRule();
	}

	//AggregatorExpression:
	//	{CountAggregator} "count";
	public PatternLanguageGrammarAccess.AggregatorExpressionElements getAggregatorExpressionAccess() {
		return gaPatternLanguage.getAggregatorExpressionAccess();
	}
	
	public ParserRule getAggregatorExpressionRule() {
		return getAggregatorExpressionAccess().getRule();
	}

	//XExpression:
	//	XAssignment;
	public XbaseGrammarAccess.XExpressionElements getXExpressionAccess() {
		return gaPatternLanguage.getXExpressionAccess();
	}
	
	public ParserRule getXExpressionRule() {
		return getXExpressionAccess().getRule();
	}

	//XAssignment returns XExpression:
	//	{XAssignment} feature=[types::JvmIdentifiableElement|FeatureCallID] OpSingleAssign value=XAssignment | XOrExpression
	//	(=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpMultiAssign])
	//	rightOperand=XAssignment)?;
	public XbaseGrammarAccess.XAssignmentElements getXAssignmentAccess() {
		return gaPatternLanguage.getXAssignmentAccess();
	}
	
	public ParserRule getXAssignmentRule() {
		return getXAssignmentAccess().getRule();
	}

	//OpSingleAssign:
	//	"=";
	public XbaseGrammarAccess.OpSingleAssignElements getOpSingleAssignAccess() {
		return gaPatternLanguage.getOpSingleAssignAccess();
	}
	
	public ParserRule getOpSingleAssignRule() {
		return getOpSingleAssignAccess().getRule();
	}

	//OpMultiAssign:
	//	"+=" | "-=";
	public XbaseGrammarAccess.OpMultiAssignElements getOpMultiAssignAccess() {
		return gaPatternLanguage.getOpMultiAssignAccess();
	}
	
	public ParserRule getOpMultiAssignRule() {
		return getOpMultiAssignAccess().getRule();
	}

	//XOrExpression returns XExpression:
	//	XAndExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpOr])
	//	rightOperand=XAndExpression)*;
	public XbaseGrammarAccess.XOrExpressionElements getXOrExpressionAccess() {
		return gaPatternLanguage.getXOrExpressionAccess();
	}
	
	public ParserRule getXOrExpressionRule() {
		return getXOrExpressionAccess().getRule();
	}

	//OpOr:
	//	"||";
	public XbaseGrammarAccess.OpOrElements getOpOrAccess() {
		return gaPatternLanguage.getOpOrAccess();
	}
	
	public ParserRule getOpOrRule() {
		return getOpOrAccess().getRule();
	}

	//XAndExpression returns XExpression:
	//	XEqualityExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpAnd])
	//	rightOperand=XEqualityExpression)*;
	public XbaseGrammarAccess.XAndExpressionElements getXAndExpressionAccess() {
		return gaPatternLanguage.getXAndExpressionAccess();
	}
	
	public ParserRule getXAndExpressionRule() {
		return getXAndExpressionAccess().getRule();
	}

	//OpAnd:
	//	"&&";
	public XbaseGrammarAccess.OpAndElements getOpAndAccess() {
		return gaPatternLanguage.getOpAndAccess();
	}
	
	public ParserRule getOpAndRule() {
		return getOpAndAccess().getRule();
	}

	//XEqualityExpression returns XExpression:
	//	XRelationalExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpEquality])
	//	rightOperand=XRelationalExpression)*;
	public XbaseGrammarAccess.XEqualityExpressionElements getXEqualityExpressionAccess() {
		return gaPatternLanguage.getXEqualityExpressionAccess();
	}
	
	public ParserRule getXEqualityExpressionRule() {
		return getXEqualityExpressionAccess().getRule();
	}

	//OpEquality:
	//	"==" | "!=" | "===" | "!==";
	public XbaseGrammarAccess.OpEqualityElements getOpEqualityAccess() {
		return gaPatternLanguage.getOpEqualityAccess();
	}
	
	public ParserRule getOpEqualityRule() {
		return getOpEqualityAccess().getRule();
	}

	//XRelationalExpression returns XExpression:
	//	XOtherOperatorExpression (=> ({XInstanceOfExpression.expression=current} "instanceof") type=JvmTypeReference | =>
	//	({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpCompare])
	//	rightOperand=XOtherOperatorExpression)*;
	public XbaseGrammarAccess.XRelationalExpressionElements getXRelationalExpressionAccess() {
		return gaPatternLanguage.getXRelationalExpressionAccess();
	}
	
	public ParserRule getXRelationalExpressionRule() {
		return getXRelationalExpressionAccess().getRule();
	}

	//OpCompare:
	//	">=" | "<=" | ">" | "<";
	public XbaseGrammarAccess.OpCompareElements getOpCompareAccess() {
		return gaPatternLanguage.getOpCompareAccess();
	}
	
	public ParserRule getOpCompareRule() {
		return getOpCompareAccess().getRule();
	}

	//XOtherOperatorExpression returns XExpression:
	//	XAdditiveExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpOther])
	//	rightOperand=XAdditiveExpression)*;
	public XbaseGrammarAccess.XOtherOperatorExpressionElements getXOtherOperatorExpressionAccess() {
		return gaPatternLanguage.getXOtherOperatorExpressionAccess();
	}
	
	public ParserRule getXOtherOperatorExpressionRule() {
		return getXOtherOperatorExpressionAccess().getRule();
	}

	//OpOther:
	//	"->" | "..<" | ">" ".." | ".." | "=>" | ">" (=> (">" ">") | ">") | "<" (=> ("<" "<") | "<") | "<>" | "?:" | "<=>";
	public XbaseGrammarAccess.OpOtherElements getOpOtherAccess() {
		return gaPatternLanguage.getOpOtherAccess();
	}
	
	public ParserRule getOpOtherRule() {
		return getOpOtherAccess().getRule();
	}

	//XAdditiveExpression returns XExpression:
	//	XMultiplicativeExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpAdd])
	//	rightOperand=XMultiplicativeExpression)*;
	public XbaseGrammarAccess.XAdditiveExpressionElements getXAdditiveExpressionAccess() {
		return gaPatternLanguage.getXAdditiveExpressionAccess();
	}
	
	public ParserRule getXAdditiveExpressionRule() {
		return getXAdditiveExpressionAccess().getRule();
	}

	//OpAdd:
	//	"+" | "-";
	public XbaseGrammarAccess.OpAddElements getOpAddAccess() {
		return gaPatternLanguage.getOpAddAccess();
	}
	
	public ParserRule getOpAddRule() {
		return getOpAddAccess().getRule();
	}

	//XMultiplicativeExpression returns XExpression:
	//	XUnaryOperation (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpMulti])
	//	rightOperand=XUnaryOperation)*;
	public XbaseGrammarAccess.XMultiplicativeExpressionElements getXMultiplicativeExpressionAccess() {
		return gaPatternLanguage.getXMultiplicativeExpressionAccess();
	}
	
	public ParserRule getXMultiplicativeExpressionRule() {
		return getXMultiplicativeExpressionAccess().getRule();
	}

	//OpMulti:
	//	"*" | "**" | "/" | "%";
	public XbaseGrammarAccess.OpMultiElements getOpMultiAccess() {
		return gaPatternLanguage.getOpMultiAccess();
	}
	
	public ParserRule getOpMultiRule() {
		return getOpMultiAccess().getRule();
	}

	//XUnaryOperation returns XExpression:
	//	{XUnaryOperation} feature=[types::JvmIdentifiableElement|OpUnary] operand=XUnaryOperation | XCastedExpression;
	public XbaseGrammarAccess.XUnaryOperationElements getXUnaryOperationAccess() {
		return gaPatternLanguage.getXUnaryOperationAccess();
	}
	
	public ParserRule getXUnaryOperationRule() {
		return getXUnaryOperationAccess().getRule();
	}

	//OpUnary:
	//	"!" | "-" | "+";
	public XbaseGrammarAccess.OpUnaryElements getOpUnaryAccess() {
		return gaPatternLanguage.getOpUnaryAccess();
	}
	
	public ParserRule getOpUnaryRule() {
		return getOpUnaryAccess().getRule();
	}

	//XCastedExpression returns XExpression:
	//	XMemberFeatureCall (=> ({XCastedExpression.target=current} "as") type=JvmTypeReference)*;
	public XbaseGrammarAccess.XCastedExpressionElements getXCastedExpressionAccess() {
		return gaPatternLanguage.getXCastedExpressionAccess();
	}
	
	public ParserRule getXCastedExpressionRule() {
		return getXCastedExpressionAccess().getRule();
	}

	//XMemberFeatureCall returns XExpression:
	//	XPrimaryExpression (=> ({XAssignment.assignable=current} ("." | explicitStatic?="::")
	//	feature=[types::JvmIdentifiableElement|FeatureCallID] OpSingleAssign) value=XAssignment | =>
	//	({XMemberFeatureCall.memberCallTarget=current} ("." | nullSafe?="?." | explicitStatic?="::")) ("<"
	//	typeArguments+=JvmArgumentTypeReference ("," typeArguments+=JvmArgumentTypeReference)* ">")?
	//	feature=[types::JvmIdentifiableElement|FeatureCallID] (=> explicitOperationCall?="("
	//	(memberCallArguments+=XShortClosure | memberCallArguments+=XExpression ("," memberCallArguments+=XExpression)*)? ")")?
	//	memberCallArguments+=XClosure?)*;
	public XbaseGrammarAccess.XMemberFeatureCallElements getXMemberFeatureCallAccess() {
		return gaPatternLanguage.getXMemberFeatureCallAccess();
	}
	
	public ParserRule getXMemberFeatureCallRule() {
		return getXMemberFeatureCallAccess().getRule();
	}

	//XPrimaryExpression returns XExpression:
	//	XConstructorCall | XBlockExpression | XSwitchExpression | XFeatureCall | XLiteral | XIfExpression | XForLoopExpression
	//	| XWhileExpression | XDoWhileExpression | XThrowExpression | XReturnExpression | XTryCatchFinallyExpression |
	//	XParenthesizedExpression;
	public XbaseGrammarAccess.XPrimaryExpressionElements getXPrimaryExpressionAccess() {
		return gaPatternLanguage.getXPrimaryExpressionAccess();
	}
	
	public ParserRule getXPrimaryExpressionRule() {
		return getXPrimaryExpressionAccess().getRule();
	}

	//XLiteral returns XExpression:
	//	XCollectionLiteral | XClosure | XBooleanLiteral | XNumberLiteral | XNullLiteral | XStringLiteral | XTypeLiteral;
	public XbaseGrammarAccess.XLiteralElements getXLiteralAccess() {
		return gaPatternLanguage.getXLiteralAccess();
	}
	
	public ParserRule getXLiteralRule() {
		return getXLiteralAccess().getRule();
	}

	//XCollectionLiteral:
	//	XSetLiteral | XListLiteral;
	public XbaseGrammarAccess.XCollectionLiteralElements getXCollectionLiteralAccess() {
		return gaPatternLanguage.getXCollectionLiteralAccess();
	}
	
	public ParserRule getXCollectionLiteralRule() {
		return getXCollectionLiteralAccess().getRule();
	}

	//XSetLiteral:
	//	{XSetLiteral} "#" "{" (elements+=XExpression ("," elements+=XExpression)*)? "}";
	public XbaseGrammarAccess.XSetLiteralElements getXSetLiteralAccess() {
		return gaPatternLanguage.getXSetLiteralAccess();
	}
	
	public ParserRule getXSetLiteralRule() {
		return getXSetLiteralAccess().getRule();
	}

	//XListLiteral:
	//	{XListLiteral} "#" "[" (elements+=XExpression ("," elements+=XExpression)*)? "]";
	public XbaseGrammarAccess.XListLiteralElements getXListLiteralAccess() {
		return gaPatternLanguage.getXListLiteralAccess();
	}
	
	public ParserRule getXListLiteralRule() {
		return getXListLiteralAccess().getRule();
	}

	//XClosure returns XExpression:
	//	=> ({XClosure} "[") => ((declaredFormalParameters+=JvmFormalParameter (","
	//	declaredFormalParameters+=JvmFormalParameter)*)? explicitSyntax?="|")? expression=XExpressionInClosure "]";
	public XbaseGrammarAccess.XClosureElements getXClosureAccess() {
		return gaPatternLanguage.getXClosureAccess();
	}
	
	public ParserRule getXClosureRule() {
		return getXClosureAccess().getRule();
	}

	//XExpressionInClosure returns XExpression:
	//	{XBlockExpression} (expressions+=XExpressionInsideBlock ";"?)*;
	public XbaseGrammarAccess.XExpressionInClosureElements getXExpressionInClosureAccess() {
		return gaPatternLanguage.getXExpressionInClosureAccess();
	}
	
	public ParserRule getXExpressionInClosureRule() {
		return getXExpressionInClosureAccess().getRule();
	}

	//XShortClosure returns XExpression:
	//	=> ({XClosure} (declaredFormalParameters+=JvmFormalParameter ("," declaredFormalParameters+=JvmFormalParameter)*)?
	//	explicitSyntax?="|") expression=XExpression;
	public XbaseGrammarAccess.XShortClosureElements getXShortClosureAccess() {
		return gaPatternLanguage.getXShortClosureAccess();
	}
	
	public ParserRule getXShortClosureRule() {
		return getXShortClosureAccess().getRule();
	}

	//XParenthesizedExpression returns XExpression:
	//	"(" XExpression ")";
	public XbaseGrammarAccess.XParenthesizedExpressionElements getXParenthesizedExpressionAccess() {
		return gaPatternLanguage.getXParenthesizedExpressionAccess();
	}
	
	public ParserRule getXParenthesizedExpressionRule() {
		return getXParenthesizedExpressionAccess().getRule();
	}

	//XIfExpression returns XExpression:
	//	{XIfExpression} "if" "(" if=XExpression ")" then=XExpression ("else" else=XExpression)?;
	public XbaseGrammarAccess.XIfExpressionElements getXIfExpressionAccess() {
		return gaPatternLanguage.getXIfExpressionAccess();
	}
	
	public ParserRule getXIfExpressionRule() {
		return getXIfExpressionAccess().getRule();
	}

	//XSwitchExpression returns XExpression:
	//	{XSwitchExpression} "switch" (=> (localVarName=ValidID ":")? switch=XExpression | => ("(" localVarName=ValidID ":")
	//	switch=XExpression ")") "{" cases+=XCasePart+ ("default" ":" default=XExpression)? "}";
	public XbaseGrammarAccess.XSwitchExpressionElements getXSwitchExpressionAccess() {
		return gaPatternLanguage.getXSwitchExpressionAccess();
	}
	
	public ParserRule getXSwitchExpressionRule() {
		return getXSwitchExpressionAccess().getRule();
	}

	//XCasePart:
	//	typeGuard=JvmTypeReference? ("case" case=XExpression)? ":" then=XExpression;
	public XbaseGrammarAccess.XCasePartElements getXCasePartAccess() {
		return gaPatternLanguage.getXCasePartAccess();
	}
	
	public ParserRule getXCasePartRule() {
		return getXCasePartAccess().getRule();
	}

	//XForLoopExpression returns XExpression:
	//	{XForLoopExpression} "for" "(" declaredParam=JvmFormalParameter ":" forExpression=XExpression ")"
	//	eachExpression=XExpression;
	public XbaseGrammarAccess.XForLoopExpressionElements getXForLoopExpressionAccess() {
		return gaPatternLanguage.getXForLoopExpressionAccess();
	}
	
	public ParserRule getXForLoopExpressionRule() {
		return getXForLoopExpressionAccess().getRule();
	}

	//XWhileExpression returns XExpression:
	//	{XWhileExpression} "while" "(" predicate=XExpression ")" body=XExpression;
	public XbaseGrammarAccess.XWhileExpressionElements getXWhileExpressionAccess() {
		return gaPatternLanguage.getXWhileExpressionAccess();
	}
	
	public ParserRule getXWhileExpressionRule() {
		return getXWhileExpressionAccess().getRule();
	}

	//XDoWhileExpression returns XExpression:
	//	{XDoWhileExpression} "do" body=XExpression "while" "(" predicate=XExpression ")";
	public XbaseGrammarAccess.XDoWhileExpressionElements getXDoWhileExpressionAccess() {
		return gaPatternLanguage.getXDoWhileExpressionAccess();
	}
	
	public ParserRule getXDoWhileExpressionRule() {
		return getXDoWhileExpressionAccess().getRule();
	}

	//XBlockExpression returns XExpression:
	//	{XBlockExpression} "{" (expressions+=XExpressionInsideBlock ";"?)* "}";
	public XbaseGrammarAccess.XBlockExpressionElements getXBlockExpressionAccess() {
		return gaPatternLanguage.getXBlockExpressionAccess();
	}
	
	public ParserRule getXBlockExpressionRule() {
		return getXBlockExpressionAccess().getRule();
	}

	//XExpressionInsideBlock returns XExpression:
	//	XVariableDeclaration | XExpression;
	public XbaseGrammarAccess.XExpressionInsideBlockElements getXExpressionInsideBlockAccess() {
		return gaPatternLanguage.getXExpressionInsideBlockAccess();
	}
	
	public ParserRule getXExpressionInsideBlockRule() {
		return getXExpressionInsideBlockAccess().getRule();
	}

	//XVariableDeclaration returns XExpression:
	//	{XVariableDeclaration} (writeable?="var" | "val") (=> (type=JvmTypeReference name=ValidID) | name=ValidID) ("="
	//	right=XExpression)?;
	public XbaseGrammarAccess.XVariableDeclarationElements getXVariableDeclarationAccess() {
		return gaPatternLanguage.getXVariableDeclarationAccess();
	}
	
	public ParserRule getXVariableDeclarationRule() {
		return getXVariableDeclarationAccess().getRule();
	}

	//JvmFormalParameter returns types::JvmFormalParameter:
	//	parameterType=JvmTypeReference? name=ValidID;
	public XbaseGrammarAccess.JvmFormalParameterElements getJvmFormalParameterAccess() {
		return gaPatternLanguage.getJvmFormalParameterAccess();
	}
	
	public ParserRule getJvmFormalParameterRule() {
		return getJvmFormalParameterAccess().getRule();
	}

	//FullJvmFormalParameter returns types::JvmFormalParameter:
	//	parameterType=JvmTypeReference name=ValidID;
	public XbaseGrammarAccess.FullJvmFormalParameterElements getFullJvmFormalParameterAccess() {
		return gaPatternLanguage.getFullJvmFormalParameterAccess();
	}
	
	public ParserRule getFullJvmFormalParameterRule() {
		return getFullJvmFormalParameterAccess().getRule();
	}

	//XFeatureCall returns XExpression:
	//	{XFeatureCall} ("<" typeArguments+=JvmArgumentTypeReference ("," typeArguments+=JvmArgumentTypeReference)* ">")?
	//	feature=[types::JvmIdentifiableElement|IdOrSuper] (=> explicitOperationCall?="(" (featureCallArguments+=XShortClosure
	//	| featureCallArguments+=XExpression ("," featureCallArguments+=XExpression)*)? ")")? featureCallArguments+=XClosure?;
	public XbaseGrammarAccess.XFeatureCallElements getXFeatureCallAccess() {
		return gaPatternLanguage.getXFeatureCallAccess();
	}
	
	public ParserRule getXFeatureCallRule() {
		return getXFeatureCallAccess().getRule();
	}

	//FeatureCallID:
	//	ValidID | "extends" | "static" | "import" | "extension";
	public XbaseGrammarAccess.FeatureCallIDElements getFeatureCallIDAccess() {
		return gaPatternLanguage.getFeatureCallIDAccess();
	}
	
	public ParserRule getFeatureCallIDRule() {
		return getFeatureCallIDAccess().getRule();
	}

	//IdOrSuper:
	//	FeatureCallID | "super";
	public XbaseGrammarAccess.IdOrSuperElements getIdOrSuperAccess() {
		return gaPatternLanguage.getIdOrSuperAccess();
	}
	
	public ParserRule getIdOrSuperRule() {
		return getIdOrSuperAccess().getRule();
	}

	//XConstructorCall returns XExpression:
	//	{XConstructorCall} "new" constructor=[types::JvmConstructor|QualifiedName] ("<"
	//	typeArguments+=JvmArgumentTypeReference ("," typeArguments+=JvmArgumentTypeReference)* ">")? ("("
	//	(arguments+=XShortClosure | arguments+=XExpression ("," arguments+=XExpression)*)? ")")? arguments+=XClosure?;
	public XbaseGrammarAccess.XConstructorCallElements getXConstructorCallAccess() {
		return gaPatternLanguage.getXConstructorCallAccess();
	}
	
	public ParserRule getXConstructorCallRule() {
		return getXConstructorCallAccess().getRule();
	}

	//XBooleanLiteral returns XExpression:
	//	{XBooleanLiteral} ("false" | isTrue?="true");
	public XbaseGrammarAccess.XBooleanLiteralElements getXBooleanLiteralAccess() {
		return gaPatternLanguage.getXBooleanLiteralAccess();
	}
	
	public ParserRule getXBooleanLiteralRule() {
		return getXBooleanLiteralAccess().getRule();
	}

	//XNullLiteral returns XExpression:
	//	{XNullLiteral} "null";
	public XbaseGrammarAccess.XNullLiteralElements getXNullLiteralAccess() {
		return gaPatternLanguage.getXNullLiteralAccess();
	}
	
	public ParserRule getXNullLiteralRule() {
		return getXNullLiteralAccess().getRule();
	}

	//XNumberLiteral returns XExpression:
	//	{XNumberLiteral} value=Number;
	public XbaseGrammarAccess.XNumberLiteralElements getXNumberLiteralAccess() {
		return gaPatternLanguage.getXNumberLiteralAccess();
	}
	
	public ParserRule getXNumberLiteralRule() {
		return getXNumberLiteralAccess().getRule();
	}

	//XStringLiteral returns XExpression:
	//	{XStringLiteral} value=STRING;
	public XbaseGrammarAccess.XStringLiteralElements getXStringLiteralAccess() {
		return gaPatternLanguage.getXStringLiteralAccess();
	}
	
	public ParserRule getXStringLiteralRule() {
		return getXStringLiteralAccess().getRule();
	}

	//XTypeLiteral returns XExpression:
	//	{XTypeLiteral} "typeof" "(" type=[types::JvmType|QualifiedName] arrayDimensions+=ArrayBrackets* ")";
	public XbaseGrammarAccess.XTypeLiteralElements getXTypeLiteralAccess() {
		return gaPatternLanguage.getXTypeLiteralAccess();
	}
	
	public ParserRule getXTypeLiteralRule() {
		return getXTypeLiteralAccess().getRule();
	}

	//XThrowExpression returns XExpression:
	//	{XThrowExpression} "throw" expression=XExpression;
	public XbaseGrammarAccess.XThrowExpressionElements getXThrowExpressionAccess() {
		return gaPatternLanguage.getXThrowExpressionAccess();
	}
	
	public ParserRule getXThrowExpressionRule() {
		return getXThrowExpressionAccess().getRule();
	}

	//XReturnExpression returns XExpression:
	//	{XReturnExpression} "return" => expression=XExpression?;
	public XbaseGrammarAccess.XReturnExpressionElements getXReturnExpressionAccess() {
		return gaPatternLanguage.getXReturnExpressionAccess();
	}
	
	public ParserRule getXReturnExpressionRule() {
		return getXReturnExpressionAccess().getRule();
	}

	//XTryCatchFinallyExpression returns XExpression:
	//	{XTryCatchFinallyExpression} "try" expression=XExpression (catchClauses+=XCatchClause+ ("finally"
	//	finallyExpression=XExpression)? | "finally" finallyExpression=XExpression);
	public XbaseGrammarAccess.XTryCatchFinallyExpressionElements getXTryCatchFinallyExpressionAccess() {
		return gaPatternLanguage.getXTryCatchFinallyExpressionAccess();
	}
	
	public ParserRule getXTryCatchFinallyExpressionRule() {
		return getXTryCatchFinallyExpressionAccess().getRule();
	}

	//XCatchClause:
	//	"catch" "(" declaredParam=FullJvmFormalParameter ")" expression=XExpression;
	public XbaseGrammarAccess.XCatchClauseElements getXCatchClauseAccess() {
		return gaPatternLanguage.getXCatchClauseAccess();
	}
	
	public ParserRule getXCatchClauseRule() {
		return getXCatchClauseAccess().getRule();
	}

	//QualifiedName:
	//	ValidID ("." ValidID)*;
	public XbaseGrammarAccess.QualifiedNameElements getQualifiedNameAccess() {
		return gaPatternLanguage.getQualifiedNameAccess();
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}

	//Number hidden():
	//	HEX | (INT | DECIMAL) ("." (INT | DECIMAL))?;
	public XbaseGrammarAccess.NumberElements getNumberAccess() {
		return gaPatternLanguage.getNumberAccess();
	}
	
	public ParserRule getNumberRule() {
		return getNumberAccess().getRule();
	}

	/// **
	// * Dummy rule, for "better" downwards compatibility, since GrammarAccess generates non-static inner classes, 
	// * which makes downstream grammars break on classloading, when a rule is removed.
	// * / StaticQualifier:
	//	(ValidID "::")+;
	public XbaseGrammarAccess.StaticQualifierElements getStaticQualifierAccess() {
		return gaPatternLanguage.getStaticQualifierAccess();
	}
	
	public ParserRule getStaticQualifierRule() {
		return getStaticQualifierAccess().getRule();
	}

	//terminal HEX:
	//	("0x" | "0X") ("0".."9" | "a".."f" | "A".."F" | "_")+ ("#" (("b" | "B") ("i" | "I") | ("l" | "L")))?;
	public TerminalRule getHEXRule() {
		return gaPatternLanguage.getHEXRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9" ("0".."9" | "_")*;
	public TerminalRule getINTRule() {
		return gaPatternLanguage.getINTRule();
	} 

	//terminal DECIMAL:
	//	INT (("e" | "E") ("+" | "-")? INT)? (("b" | "B") ("i" | "I" | "d" | "D") | ("l" | "L" | "d" | "D" | "f" | "F"))?;
	public TerminalRule getDECIMALRule() {
		return gaPatternLanguage.getDECIMALRule();
	} 

	//JvmTypeReference:
	//	JvmParameterizedTypeReference => ({JvmGenericArrayTypeReference.componentType=current} ArrayBrackets)* |
	//	XFunctionTypeRef;
	public XtypeGrammarAccess.JvmTypeReferenceElements getJvmTypeReferenceAccess() {
		return gaPatternLanguage.getJvmTypeReferenceAccess();
	}
	
	public ParserRule getJvmTypeReferenceRule() {
		return getJvmTypeReferenceAccess().getRule();
	}

	//ArrayBrackets:
	//	"[" "]";
	public XtypeGrammarAccess.ArrayBracketsElements getArrayBracketsAccess() {
		return gaPatternLanguage.getArrayBracketsAccess();
	}
	
	public ParserRule getArrayBracketsRule() {
		return getArrayBracketsAccess().getRule();
	}

	//XFunctionTypeRef:
	//	("(" (paramTypes+=JvmTypeReference ("," paramTypes+=JvmTypeReference)*)? ")")? "=>" returnType=JvmTypeReference;
	public XtypeGrammarAccess.XFunctionTypeRefElements getXFunctionTypeRefAccess() {
		return gaPatternLanguage.getXFunctionTypeRefAccess();
	}
	
	public ParserRule getXFunctionTypeRefRule() {
		return getXFunctionTypeRefAccess().getRule();
	}

	//JvmParameterizedTypeReference:
	//	type=[JvmType|QualifiedName] ("<" arguments+=JvmArgumentTypeReference ("," arguments+=JvmArgumentTypeReference)*
	//	">")?;
	public XtypeGrammarAccess.JvmParameterizedTypeReferenceElements getJvmParameterizedTypeReferenceAccess() {
		return gaPatternLanguage.getJvmParameterizedTypeReferenceAccess();
	}
	
	public ParserRule getJvmParameterizedTypeReferenceRule() {
		return getJvmParameterizedTypeReferenceAccess().getRule();
	}

	//JvmArgumentTypeReference returns JvmTypeReference:
	//	JvmTypeReference | JvmWildcardTypeReference;
	public XtypeGrammarAccess.JvmArgumentTypeReferenceElements getJvmArgumentTypeReferenceAccess() {
		return gaPatternLanguage.getJvmArgumentTypeReferenceAccess();
	}
	
	public ParserRule getJvmArgumentTypeReferenceRule() {
		return getJvmArgumentTypeReferenceAccess().getRule();
	}

	//JvmWildcardTypeReference:
	//	{JvmWildcardTypeReference} "?" (constraints+=JvmUpperBound | constraints+=JvmLowerBound)?;
	public XtypeGrammarAccess.JvmWildcardTypeReferenceElements getJvmWildcardTypeReferenceAccess() {
		return gaPatternLanguage.getJvmWildcardTypeReferenceAccess();
	}
	
	public ParserRule getJvmWildcardTypeReferenceRule() {
		return getJvmWildcardTypeReferenceAccess().getRule();
	}

	//JvmUpperBound:
	//	"extends" typeReference=JvmTypeReference;
	public XtypeGrammarAccess.JvmUpperBoundElements getJvmUpperBoundAccess() {
		return gaPatternLanguage.getJvmUpperBoundAccess();
	}
	
	public ParserRule getJvmUpperBoundRule() {
		return getJvmUpperBoundAccess().getRule();
	}

	//JvmUpperBoundAnded returns JvmUpperBound:
	//	"&" typeReference=JvmTypeReference;
	public XtypeGrammarAccess.JvmUpperBoundAndedElements getJvmUpperBoundAndedAccess() {
		return gaPatternLanguage.getJvmUpperBoundAndedAccess();
	}
	
	public ParserRule getJvmUpperBoundAndedRule() {
		return getJvmUpperBoundAndedAccess().getRule();
	}

	//JvmLowerBound:
	//	"super" typeReference=JvmTypeReference;
	public XtypeGrammarAccess.JvmLowerBoundElements getJvmLowerBoundAccess() {
		return gaPatternLanguage.getJvmLowerBoundAccess();
	}
	
	public ParserRule getJvmLowerBoundRule() {
		return getJvmLowerBoundAccess().getRule();
	}

	//JvmTypeParameter:
	//	name=ValidID (constraints+=JvmUpperBound constraints+=JvmUpperBoundAnded* | constraints+=JvmLowerBound)?;
	public XtypeGrammarAccess.JvmTypeParameterElements getJvmTypeParameterAccess() {
		return gaPatternLanguage.getJvmTypeParameterAccess();
	}
	
	public ParserRule getJvmTypeParameterRule() {
		return getJvmTypeParameterAccess().getRule();
	}

	//QualifiedNameWithWildcard:
	//	QualifiedName "." "*";
	public XtypeGrammarAccess.QualifiedNameWithWildcardElements getQualifiedNameWithWildcardAccess() {
		return gaPatternLanguage.getQualifiedNameWithWildcardAccess();
	}
	
	public ParserRule getQualifiedNameWithWildcardRule() {
		return getQualifiedNameWithWildcardAccess().getRule();
	}

	//ValidID:
	//	ID;
	public XtypeGrammarAccess.ValidIDElements getValidIDAccess() {
		return gaPatternLanguage.getValidIDAccess();
	}
	
	public ParserRule getValidIDRule() {
		return getValidIDAccess().getRule();
	}

	//XImportSection:
	//	importDeclarations+=XImportDeclaration+;
	public XtypeGrammarAccess.XImportSectionElements getXImportSectionAccess() {
		return gaPatternLanguage.getXImportSectionAccess();
	}
	
	public ParserRule getXImportSectionRule() {
		return getXImportSectionAccess().getRule();
	}

	//XImportDeclaration:
	//	"import" (static?="static" extension?="extension"? importedType=[JvmDeclaredType|QualifiedName] "." "*" |
	//	importedType=[JvmDeclaredType|QualifiedName] | importedNamespace=QualifiedNameWithWildcard) ";"?;
	public XtypeGrammarAccess.XImportDeclarationElements getXImportDeclarationAccess() {
		return gaPatternLanguage.getXImportDeclarationAccess();
	}
	
	public ParserRule getXImportDeclarationRule() {
		return getXImportDeclarationAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "$" | "_") ("a".."z" | "A".."Z" | "$" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaPatternLanguage.getIDRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaPatternLanguage.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaPatternLanguage.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaPatternLanguage.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaPatternLanguage.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaPatternLanguage.getANY_OTHERRule();
	} 
}
