/*
 * generated by Xtext 2.9.0.beta5
 */
package org.eclipse.incquery.patternlanguage.rdf;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.incquery.patternlanguage.PatternLanguageStandaloneSetup;
import org.eclipse.xtext.ISetup;

@SuppressWarnings("all")
public class RdfPatternLanguageStandaloneSetupGenerated implements ISetup {

	@Override
	public Injector createInjectorAndDoEMFRegistration() {
		PatternLanguageStandaloneSetup.doSetup();

		Injector injector = createInjector();
		register(injector);
		return injector;
	}
	
	public Injector createInjector() {
		return Guice.createInjector(new RdfPatternLanguageRuntimeModule());
	}
	
	public void register(Injector injector) {
		
		
		if (!EPackage.Registry.INSTANCE.containsKey("http://www.eclipse.org/incquery/patternlanguage/rdf/RdfPatternLanguage")) {
		EPackage.Registry.INSTANCE.put("http://www.eclipse.org/incquery/patternlanguage/rdf/RdfPatternLanguage", org.eclipse.incquery.patternlanguage.rdf.rdfPatternLanguage.RdfPatternLanguagePackage.eINSTANCE);
		}
		
		
		org.eclipse.xtext.resource.IResourceFactory resourceFactory = injector.getInstance(org.eclipse.xtext.resource.IResourceFactory.class);
		org.eclipse.xtext.resource.IResourceServiceProvider serviceProvider = injector.getInstance(org.eclipse.xtext.resource.IResourceServiceProvider.class);
		
		Resource.Factory.Registry.INSTANCE.getExtensionToFactoryMap().put("rdfiq", resourceFactory);
		org.eclipse.xtext.resource.IResourceServiceProvider.Registry.INSTANCE.getExtensionToFactoryMap().put("rdfiq", serviceProvider);
		
		
	}
}
