/*
 * generated by Xtext
 */
package org.eclipse.incquery.patternlanguage.rdf;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RdfPatternLanguageRuntimeModule extends org.eclipse.incquery.patternlanguage.rdf.AbstractRdfPatternLanguageRuntimeModule {

}
