/**
 * generated by Xtext 2.9.0.beta5
 */
package org.eclipse.incquery.patternlanguage.rdf;

import com.google.inject.Binder;
import com.google.inject.binder.AnnotatedBindingBuilder;
import org.eclipse.incquery.patternlanguage.rdf.AbstractRdfPatternLanguageRuntimeModule;
import org.eclipse.incquery.patternlanguage.rdf.conversion.RdfPatternLanguageValueConverterService;
import org.eclipse.incquery.patternlanguage.typing.ITypeInferrer;
import org.eclipse.incquery.patternlanguage.typing.ITypeSystem;
import org.eclipse.xtext.conversion.IValueConverterService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class RdfPatternLanguageRuntimeModule extends AbstractRdfPatternLanguageRuntimeModule {
  @Override
  public Class<? extends IValueConverterService> bindIValueConverterService() {
    return RdfPatternLanguageValueConverterService.class;
  }
  
  @Override
  public void configure(final Binder binder) {
    super.configure(binder);
    AnnotatedBindingBuilder<ITypeInferrer> _bind = binder.<ITypeInferrer>bind(ITypeInferrer.class);
    _bind.to(ITypeInferrer.NullTypeInferrer.class);
    AnnotatedBindingBuilder<ITypeSystem> _bind_1 = binder.<ITypeSystem>bind(ITypeSystem.class);
    _bind_1.to(ITypeSystem.NullTypeSystem.class);
  }
}
