/**
 * generated by Xtext 2.9.0.beta5
 */
package org.eclipse.incquery.patternlanguage.rdf;

import org.eclipse.incquery.patternlanguage.rdf.RdfPatternLanguageStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class RdfPatternLanguageStandaloneSetup extends RdfPatternLanguageStandaloneSetupGenerated {
  public static void doSetup() {
    RdfPatternLanguageStandaloneSetup _rdfPatternLanguageStandaloneSetup = new RdfPatternLanguageStandaloneSetup();
    _rdfPatternLanguageStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
