/*
 * generated by Xtext
 */
package org.eclipse.incquery.patternlanguage.mondix.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MondixPatternLanguageUiModule extends org.eclipse.incquery.patternlanguage.mondix.ui.AbstractMondixPatternLanguageUiModule {
	public MondixPatternLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
