/**
 * generated by Xtext
 */
package hu.bme.mit.incqueryd.arch.language.serializer;

import hu.bme.mit.incqueryd.arch.language.serializer.AbstractArchLanguageSemanticSequencer;

@SuppressWarnings("all")
public class ArchLanguageSemanticSequencer extends AbstractArchLanguageSemanticSequencer {
}
