/*
 * generated by Xtext
 */
package hu.bme.mit.incqueryd.mondixschema.language;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MondixSchemaRuntimeModule extends hu.bme.mit.incqueryd.mondixschema.language.AbstractMondixSchemaRuntimeModule {

}
