grammar hu.bme.mit.incqueryd.mondixschema.language.MondixSchema with org.eclipse.xtext.common.Terminals

import "http://incquery.net/mondixschema"
import "http://www.eclipse.org/emf/2002/Ecore" as ecore

Schema returns Schema:
	{Schema}
	'schema' name=ID
	relations+=Relation*;

Relation returns Relation:
	{Relation}
	'relation' name=ID '{'
	columns+=Column*
	'}';

Column returns Column:
	{Column}
	'column' name=ID;
