/**
 * generated by Xtext 2.9.0.rc2
 */
package org.eclipse.incquery.patternlanguage.rdf.rdfPatternLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.eclipse.incquery.patternlanguage.rdf.rdfPatternLanguage.RdfPatternLanguagePackage#getVariable()
 * @model
 * @generated
 */
public interface Variable extends org.eclipse.incquery.patternlanguage.patternLanguage.Variable
{
} // Variable
