/*
 * generated by Xtext 2.9.0.rc2
 */
package org.eclipse.incquery.patternlanguage.rdf.web

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register additional components to be used within the web application.
 */
@FinalFieldsConstructor
class RdfPatternLanguageWebModule extends AbstractRdfPatternLanguageWebModule {
}
