Vagrant.configure("2") do |config|
  config.vm.box = "precise64"
  config.vm.provision :puppet do |puppet|
  	puppet.module_path = "modules"
    puppet.facter = {
      "fqdn" => "faunus-vm"
    }
  end
  config.vm.network :private_network, ip: "192.168.101.101"
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", "5000"]
  end
  config.vm.hostname = "faunus-vm"
end
