/*
* generated by Xtext
*/
package hu.bme.mit.incqueryd.arch.language;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ArchLanguageStandaloneSetup extends ArchLanguageStandaloneSetupGenerated{

	public static void doSetup() {
		new ArchLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

