/*
 * generated by Xtext
 */
package hu.bme.mit.incqueryd.arch.language;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ArchLanguageRuntimeModule extends hu.bme.mit.incqueryd.arch.language.AbstractArchLanguageRuntimeModule {

}
